In [3]:
import pandas as pd

In [4]:
dataframe_customers = pd.read_csv(r'./churn_customers.csv')

### CUSTOMERS INFOS

In [5]:
# 5 PRIMEIROS CLIENTES
dataframe_customers.head(5)

customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [6]:
# 5 ULTIMOS CLIENTES
dataframe_customers.tail(5)

customerID  gender  SeniorCitizen Partner Dependents
7038  6840-RESVB    Male              0     Yes        Yes
7039  2234-XADUH  Female              0     Yes        Yes
7040  4801-JZAZL  Female              0     Yes        Yes
7041  8361-LTMKD    Male              1     Yes         No
7042  3186-AJIEK    Male              0      No         No

In [7]:
# CLIENTE SCHEMA
dataframe_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64 
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB


### CONTRACTS INFOS

In [8]:
dataframe_contracts = pd.read_csv(r'./churn_contracts.csv')

In [9]:
# 5 PRIMEIROS CONTRATOS
dataframe_contracts.head(5)

customerID  tenure        Contract PaperlessBilling  \
0  7590-VHVEG       1  Month-to-month              Yes   
1  5575-GNVDE      34        One year               No   
2  3668-QPYBK       2  Month-to-month              Yes   
3  7795-CFOCW      45        One year               No   
4  9237-HQITU       2  Month-to-month              Yes   

               PaymentMethod  MonthlyCharges TotalCharges Churn  
0           Electronic check           29.85        29.85    No  
1               Mailed check           56.95       1889.5    No  
2               Mailed check           53.85       108.15   Yes  
3  Bank transfer (automatic)           42.30      1840.75    No  
4           Electronic check           70.70       151.65   Yes

In [10]:
# CONTRATOS SCHEMA
dataframe_contracts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   tenure            7043 non-null   int64  
 2   Contract          7043 non-null   object 
 3   PaperlessBilling  7043 non-null   object 
 4   PaymentMethod     7043 non-null   object 
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7043 non-null   object 
 7   Churn             7043 non-null   object 
dtypes: float64(1), int64(1), object(6)
memory usage: 440.3+ KB


### SERVICES INFOS

In [11]:
dataframe_services = pd.read_csv(r'./churn_services.csv')

In [12]:
# 5 PRIMEIROS SERVIÇOS
dataframe_services.head(5)

customerID PhoneService     MultipleLines InternetService OnlineSecurity  \
0  7590-VHVEG           No  No phone service             DSL             No   
1  5575-GNVDE          Yes                No             DSL            Yes   
2  3668-QPYBK          Yes                No             DSL            Yes   
3  7795-CFOCW           No  No phone service             DSL            Yes   
4  9237-HQITU          Yes                No     Fiber optic             No   

  OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies  
0          Yes               No          No          No              No  
1           No              Yes          No          No              No  
2          Yes               No          No          No              No  
3           No              Yes         Yes          No              No  
4           No               No          No          No              No

In [13]:
# SERVIÇOS SCHEMA
dataframe_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   customerID        7043 non-null   object
 1   PhoneService      7043 non-null   object
 2   MultipleLines     7043 non-null   object
 3   InternetService   7043 non-null   object
 4   OnlineSecurity    7043 non-null   object
 5   OnlineBackup      7043 non-null   object
 6   DeviceProtection  7043 non-null   object
 7   TechSupport       7043 non-null   object
 8   StreamingTV       7043 non-null   object
 9   StreamingMovies   7043 non-null   object
dtypes: object(10)
memory usage: 550.4+ KB


### MUDANDO ESTRUTURA CONTRACTS (SCHEMAS)

In [14]:
# errors='coerce' DEIXA OS DADOS QUE NÃO FOR POSSÍVEL CONVERTER COMO NULL
dataframe_contracts['TotalCharges'] = pd.to_numeric(dataframe_contracts['TotalCharges'], errors='coerce')

dataframe_contracts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   tenure            7043 non-null   int64  
 2   Contract          7043 non-null   object 
 3   PaperlessBilling  7043 non-null   object 
 4   PaymentMethod     7043 non-null   object 
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7032 non-null   float64
 7   Churn             7043 non-null   object 
dtypes: float64(2), int64(1), object(5)
memory usage: 440.3+ KB


11 itens ficaram ausentes (missing values)

### RENOMEAR COLUNA


In [15]:
# MODIFICANDO APENAS UMA ÚNICA COLUNA
dataframe_customers.rename(columns={'SeniorCitizen': '+65'}, inplace=True)

dataframe_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   customerID  7043 non-null   object
 1   gender      7043 non-null   object
 2   +65         7043 non-null   int64 
 3   Partner     7043 non-null   object
 4   Dependents  7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB


In [16]:
# MODIFICANDO VARIAS COLUNAS
dataframe_customers.columns = ['usuarioID', 'genero', '+65', 'casado', 'dependentes']

dataframe_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   usuarioID    7043 non-null   object
 1   genero       7043 non-null   object
 2   +65          7043 non-null   int64 
 3   casado       7043 non-null   object
 4   dependentes  7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB


### MERGE (CONECTANDO VARIOS DATAFRAMES)

In [17]:
# FIZEMOS O MERGE E O DROP DOS IDS PARA NAO DUPLICAR A INFORMAÇÃO IGUAL
dataframe_all_infos = dataframe_customers.merge(
    dataframe_contracts, left_on=['usuarioID'], right_on=['customerID']).drop(
        columns=['customerID'], axis=1).merge(
            dataframe_services, left_on=['usuarioID'], right_on=['customerID']).drop(
                 columns=['customerID'], axis=1
            )

dataframe_all_infos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   usuarioID         7043 non-null   object 
 1   genero            7043 non-null   object 
 2   +65               7043 non-null   int64  
 3   casado            7043 non-null   object 
 4   dependentes       7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   Contract          7043 non-null   object 
 7   PaperlessBilling  7043 non-null   object 
 8   PaymentMethod     7043 non-null   object 
 9   MonthlyCharges    7043 non-null   float64
 10  TotalCharges      7032 non-null   float64
 11  Churn             7043 non-null   object 
 12  PhoneService      7043 non-null   object 
 13  MultipleLines     7043 non-null   object 
 14  InternetService   7043 non-null   object 
 15  OnlineSecurity    7043 non-null   object 
 16  OnlineBackup      7043 non-null   object 


### LIDANDO COM DADOS AUSENTES

In [18]:
# DE TODAS AS COLUNAS, QUERO A SOMA DE QUANTOS DADOS SAO NA
dataframe_all_infos.isna().sum()

usuarioID            0
genero               0
+65                  0
casado               0
dependentes          0
tenure               0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
dtype: int64

In [19]:
# QUAIS DADOS DO DATAFRAME ESTÃO AUSENTES
# OBS: QUANDO ELE FALA DE LINHAS, ELE QUER DIZER X -> HORIZONTAL 0 / Y -> VERTICAL 1
dataframe_all_infos[dataframe_all_infos.isna().any(axis=1)]

usuarioID  genero  +65 casado dependentes  tenure  Contract  \
488   4472-LVYGI  Female    0    Yes         Yes       0  Two year   
753   3115-CZMZD    Male    0     No         Yes       0  Two year   
936   5709-LVOEQ  Female    0    Yes         Yes       0  Two year   
1082  4367-NUYAO    Male    0    Yes         Yes       0  Two year   
1340  1371-DWPAZ  Female    0    Yes         Yes       0  Two year   
3331  7644-OMVMY    Male    0    Yes         Yes       0  Two year   
3826  3213-VVOLG    Male    0    Yes         Yes       0  Two year   
4380  2520-SGTTA  Female    0    Yes         Yes       0  Two year   
5218  2923-ARZLG    Male    0    Yes         Yes       0  One year   
6670  4075-WKNIU  Female    0    Yes         Yes       0  Two year   
6754  2775-SEFEE    Male    0     No         Yes       0  Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges  ...  Churn  \
488               Yes  Bank transfer (automatic)           52.55  ...     No   
753                No               Mailed check           20.25  ...     No   
936                No               Mailed check           80.85  ...     No   
1082               No               Mailed check           25.75  ...     No   
1340               No    Credit card (automatic)           56.05  ...     No   
3331               No               Mailed check           19.85  ...     No   
3826               No               Mailed check           25.35  ...     No   
4380               No               Mailed check           20.00  ...     No   
5218              Yes               Mailed check           19.70  ...     No   
6670               No               Mailed check           73.35  ...     No   
6754              Yes  Bank transfer (automatic)           61.90  ...     No   

     PhoneService     MultipleLines InternetService       OnlineSecurity  \
488            No  No phone service             DSL                  Yes   
753           Yes                No              No  No internet service   
936           Yes                No             DSL                  Yes   
1082          Yes               Yes              No  No internet service   
1340           No  No phone service             DSL                  Yes   
3331          Yes                No              No  No internet service   
3826          Yes               Yes              No  No internet service   
4380          Yes                No              No  No internet service   
5218          Yes                No              No  No internet service   
6670          Yes               Yes             DSL                   No   
6754          Yes               Yes             DSL                  Yes   

             OnlineBackup     DeviceProtection          TechSupport  \
488                    No                  Yes                  Yes   
753   No internet service  No internet service  No internet service   
936                   Yes                  Yes                   No   
1082  No internet service  No internet service  No internet service   
1340                  Yes                  Yes                  Yes   
3331  No internet service  No internet service  No internet service   
3826  No internet service  No internet service  No internet service   
4380  No internet service  No internet service  No internet service   
5218  No internet service  No internet service  No internet service   
6670                  Yes                  Yes                  Yes   
6754                  Yes                   No                  Yes   

              StreamingTV      StreamingMovies  
488                   Yes                   No  
753   No internet service  No internet service  
936                   Yes                  Yes  
1082  No internet service  No internet service  
1340                  Yes                   No  
3331  No internet service  No internet service  
3826  No internet service  No internet service  
4380  No internet service  No internet service 

In [20]:
# QUANTAS COLUNAS DO DATAFRAME TEM PELO MENOS 1 DADO NAN
dataframe_all_infos.isna().any(axis=0).sum()

np.int64(1)

### MANIPULAR VALORES AUSENTES

In [ ]:
# TROCANDO OS VALORES NULOS DA COLUNA TOTALCHARGES PARA 0
dataframe_all_infos.fillna(value={ 'TotalCahrges': 0 })

usuarioID  genero  +65 casado dependentes  tenure        Contract  \
0     7590-VHVEG  Female    0    Yes          No       1  Month-to-month   
1     5575-GNVDE    Male    0     No          No      34        One year   
2     3668-QPYBK    Male    0     No          No       2  Month-to-month   
3     7795-CFOCW    Male    0     No          No      45        One year   
4     9237-HQITU  Female    0     No          No       2  Month-to-month   
...          ...     ...  ...    ...         ...     ...             ...   
7038  6840-RESVB    Male    0    Yes         Yes      24        One year   
7039  2234-XADUH  Female    0    Yes         Yes      72        One year   
7040  4801-JZAZL  Female    0    Yes         Yes      11  Month-to-month   
7041  8361-LTMKD    Male    1    Yes          No       4  Month-to-month   
7042  3186-AJIEK    Male    0     No          No      66        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges  ...  Churn  \
0                 Yes           Electronic check           29.85  ...     No   
1                  No               Mailed check           56.95  ...     No   
2                 Yes               Mailed check           53.85  ...    Yes   
3                  No  Bank transfer (automatic)           42.30  ...     No   
4                 Yes           Electronic check           70.70  ...    Yes   
...               ...                        ...             ...  ...    ...   
7038              Yes               Mailed check           84.80  ...     No   
7039              Yes    Credit card (automatic)          103.20  ...     No   
7040              Yes           Electronic check           29.60  ...     No   
7041              Yes               Mailed check           74.40  ...    Yes   
7042              Yes  Bank transfer (automatic)          105.65  ...     No   

     PhoneService     MultipleLines InternetService OnlineSecurity  \
0              No  No phone service             DSL             No   
1             Yes                No             DSL            Yes   
2             Yes                No             DSL            Yes   
3              No  No phone service             DSL            Yes   
4             Yes                No     Fiber optic             No   
...           ...               ...             ...            ...   
7038          Yes               Yes             DSL            Yes   
7039          Yes               Yes     Fiber optic             No   
7040           No  No phone service             DSL            Yes   
7041          Yes               Yes     Fiber optic             No   
7042          Yes                No     Fiber optic            Yes   

     OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies  
0             Yes               No          No          No              No  
1              No              Yes          No          No              No  
2             Yes               No          No          No              No  
3              No              Yes         Yes          No              No  
4              No               No          No          No              No  
...           ...              ...         ...         ...             ...  
7038           No              Yes         Yes         Yes             Yes  
7039          Yes              Yes          No         Yes             Yes  
7040           No               No          No          No              No  
7041           No               No          No          No              No  
7042           No              Yes         Yes         Yes             Yes  

[7043 rows x 21 columns]

In [24]:
# DROPANDO COLUNAS QUE CONTEM VALORES NULOS
dataframe_all_infos.dropna(axis=1)

usuarioID  genero  +65 casado dependentes  tenure        Contract  \
0     7590-VHVEG  Female    0    Yes          No       1  Month-to-month   
1     5575-GNVDE    Male    0     No          No      34        One year   
2     3668-QPYBK    Male    0     No          No       2  Month-to-month   
3     7795-CFOCW    Male    0     No          No      45        One year   
4     9237-HQITU  Female    0     No          No       2  Month-to-month   
...          ...     ...  ...    ...         ...     ...             ...   
7038  6840-RESVB    Male    0    Yes         Yes      24        One year   
7039  2234-XADUH  Female    0    Yes         Yes      72        One year   
7040  4801-JZAZL  Female    0    Yes         Yes      11  Month-to-month   
7041  8361-LTMKD    Male    1    Yes          No       4  Month-to-month   
7042  3186-AJIEK    Male    0     No          No      66        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges Churn  \
0                 Yes           Electronic check           29.85    No   
1                  No               Mailed check           56.95    No   
2                 Yes               Mailed check           53.85   Yes   
3                  No  Bank transfer (automatic)           42.30    No   
4                 Yes           Electronic check           70.70   Yes   
...               ...                        ...             ...   ...   
7038              Yes               Mailed check           84.80    No   
7039              Yes    Credit card (automatic)          103.20    No   
7040              Yes           Electronic check           29.60    No   
7041              Yes               Mailed check           74.40   Yes   
7042              Yes  Bank transfer (automatic)          105.65    No   

     PhoneService     MultipleLines InternetService OnlineSecurity  \
0              No  No phone service             DSL             No   
1             Yes                No             DSL            Yes   
2             Yes                No             DSL            Yes   
3              No  No phone service             DSL            Yes   
4             Yes                No     Fiber optic             No   
...           ...               ...             ...            ...   
7038          Yes               Yes             DSL            Yes   
7039          Yes               Yes     Fiber optic             No   
7040           No  No phone service             DSL            Yes   
7041          Yes               Yes     Fiber optic             No   
7042          Yes                No     Fiber optic            Yes   

     OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies  
0             Yes               No          No          No              No  
1              No              Yes          No          No              No  
2             Yes               No          No          No              No  
3              No              Yes         Yes          No              No  
4              No               No          No          No              No  
...           ...              ...         ...         ...             ...  
7038           No              Yes         Yes         Yes             Yes  
7039          Yes              Yes          No         Yes             Yes  
7040           No               No          No          No              No  
7041           No               No          No          No              No  
7042           No              Yes         Yes         Yes             Yes  

[7043 rows x 20 columns]

NUMERO DE COLUNAS ABAIXOU DE 21 PARA 20

In [25]:
# DROPANDO LINHAS QUE CONTEM VALORES NULOS
dataframe_all_infos.dropna(axis=0)

usuarioID  genero  +65 casado dependentes  tenure        Contract  \
0     7590-VHVEG  Female    0    Yes          No       1  Month-to-month   
1     5575-GNVDE    Male    0     No          No      34        One year   
2     3668-QPYBK    Male    0     No          No       2  Month-to-month   
3     7795-CFOCW    Male    0     No          No      45        One year   
4     9237-HQITU  Female    0     No          No       2  Month-to-month   
...          ...     ...  ...    ...         ...     ...             ...   
7038  6840-RESVB    Male    0    Yes         Yes      24        One year   
7039  2234-XADUH  Female    0    Yes         Yes      72        One year   
7040  4801-JZAZL  Female    0    Yes         Yes      11  Month-to-month   
7041  8361-LTMKD    Male    1    Yes          No       4  Month-to-month   
7042  3186-AJIEK    Male    0     No          No      66        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges  ...  Churn  \
0                 Yes           Electronic check           29.85  ...     No   
1                  No               Mailed check           56.95  ...     No   
2                 Yes               Mailed check           53.85  ...    Yes   
3                  No  Bank transfer (automatic)           42.30  ...     No   
4                 Yes           Electronic check           70.70  ...    Yes   
...               ...                        ...             ...  ...    ...   
7038              Yes               Mailed check           84.80  ...     No   
7039              Yes    Credit card (automatic)          103.20  ...     No   
7040              Yes           Electronic check           29.60  ...     No   
7041              Yes               Mailed check           74.40  ...    Yes   
7042              Yes  Bank transfer (automatic)          105.65  ...     No   

     PhoneService     MultipleLines InternetService OnlineSecurity  \
0              No  No phone service             DSL             No   
1             Yes                No             DSL            Yes   
2             Yes                No             DSL            Yes   
3              No  No phone service             DSL            Yes   
4             Yes                No     Fiber optic             No   
...           ...               ...             ...            ...   
7038          Yes               Yes             DSL            Yes   
7039          Yes               Yes     Fiber optic             No   
7040           No  No phone service             DSL            Yes   
7041          Yes               Yes     Fiber optic             No   
7042          Yes                No     Fiber optic            Yes   

     OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies  
0             Yes               No          No          No              No  
1              No              Yes          No          No              No  
2             Yes               No          No          No              No  
3              No              Yes         Yes          No              No  
4              No               No          No          No              No  
...           ...              ...         ...         ...             ...  
7038           No              Yes         Yes         Yes             Yes  
7039          Yes              Yes          No         Yes             Yes  
7040           No               No          No          No              No  
7041           No               No          No          No              No  
7042           No              Yes         Yes         Yes             Yes  

[7032 rows x 21 columns]

NUMERO DE LINHAS ABAIXOU DE 7043 PARA 7032